import React from 'react';

const TravelContent: React.FC = () => {
  return (
    <div style={{ height: '100vh', width: '100%' }}>
      <h2>Travel</h2>
      <p>Every airport I've been to and every flight I've taken. Autogenerated with AI (Deepseek) parsing my email inbox</p>
      <iframe 
        src="/globe.html" 
        title="Travel Globe" 
        style={{ 
          width: '150%', 
          height: 'calc(100vh - 150px)', 
          border: 'none',
          marginTop: '10px'
        }}
      />
    </div>
  );
};

export default TravelContent; 